image: "python:3.6.5"

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv env
  - source env/bin/activate
  - pip install -r requirements.txt

stages:
  - setup
  - test
  - coverage

test:
  stage: test
  script:
    - pytest

coverage:
  stage: coverage
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    paths:
      - htmlcov/
  script:
    - coverage run --source=. -m pytest
    - coverage html
    - coverage report -m ./*
