# http://flask.pocoo.org/docs/1.0/config/

# FLASK
FLASK_DEBUG = True

# SQLALCHEMY
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_DATABASE_URI = "sqlite:///flask.sqlite"

# MONGO
MONGODB_DB = 'flask-grupy'
MONGODB_HOST = 'localhost'
MONGODB_PORT = 27017
MONGODB_USERNAME = 'flask'
MONGODB_PASSWORD = 'grupy'

JWT_TOKEN_LOCATION=['headers']
JWT_ACCESS_TOKEN_EXPIRES=20
JWT_REFRESH_TOKEN_EXPIRES=1800
SECRET_KEY = 'fl4sk-grupI'