version: '3'
services:
  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: flask
      MONGO_INITDB_ROOT_PASSWORD: grupy
    restart: always
    volumes:
      - mongodb-data:/data/db
  server:
    container_name: server
    hostname: server
    image: python:3.6
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    volumes:
      - .:/flask-grupy
    restart: always
    command: bash -c "cd flask-run/ && flask run"

volumes:
  mongodb-data:
